version: '3'

tasks:
  build:
    cmds:
      # Apple Silicon
      - GOOS=darwin GOARCH=arm64 go build -o dist/pruner-arm64-darwin main.go
      # 64-bit
      - GOOS=linux GOARCH=amd64 go build -o dist/pruner-amd64-linux main.go
      - GOOS=darwin GOARCH=amd64 go build -o dist/pruner-amd64-darwin main.go
      - GOOS=windows GOARCH=amd64 go build -o dist/pruner-amd64-windows main.go
      # 32-bit
      - GOOS=linux GOARCH=386 go build -o dist/pruner-386-linux main.go
      - GOOS=windows GOARCH=386 go build -o dist/pruner-386-windows main.go